name: Pull Requests

on:
  pull_request:

permissions: {}

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pull-request-validation:
    name: Check / Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # we don't know what commit the last tag was it's safer to get entire repo so previousStableVersion resolves
          fetch-depth: 0

      - name: Setup Java 8
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Cache Coursier cache
        uses: coursier/cache-action@v6.4.0

      - name: Enable jvm-opts
        run: cp .jvmopts-ci .jvmopts

      - name: sbt validateCompile
        run: |-
          sbt \
          -Dpekko.mima.enabled=false \
          -Dpekko.test.multi-in-test=false \
          -Dpekko.test.timefactor=2 \
          -Dpekko.actor.testkit.typed.timefactor=2 \
          -Dpekko.test.tags.exclude=gh-exclude,timing \
          -Dpekko.cluster.assert=on \
          -Dsbt.override.build.repos=false \
          -Dpekko.test.multi-node=false \
          -Dsbt.log.noformat=false \
          -Dpekko.log.timestamps=true \
          validateCompile

      - name: sbt validatePullRequest
        run: |-
          sbt \
          -Dpekko.mima.enabled=false \
          -Dpekko.test.multi-in-test=false \
          -Dpekko.test.timefactor=2 \
          -Dpekko.actor.testkit.typed.timefactor=2 \
          -Dpekko.test.tags.exclude=gh-exclude,timing \
          -Dpekko.cluster.assert=on \
          -Dsbt.override.build.repos=false \
          -Dpekko.test.multi-node=false \
          -Dsbt.log.noformat=false \
          -Dpekko.log.timestamps=true \
          validatePullRequest
